#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2025 Ilya Egorov <0x42005e1f@gmail.com>
# SPDX-License-Identifier: ISC

from aiologic.meta import DEFAULT, DefaultType

from ._executors import TaskExecutor

def _get_threading_cancelled_exc_class() -> type[BaseException]: ...
def _get_eventlet_cancelled_exc_class() -> type[BaseException]: ...
def _get_gevent_cancelled_exc_class() -> type[BaseException]: ...
def _get_asyncio_cancelled_exc_class() -> type[BaseException]: ...
def _get_curio_cancelled_exc_class() -> type[BaseException]: ...
def _get_trio_cancelled_exc_class() -> type[BaseException]: ...
def get_cancelled_exc_class(
    *,
    executor: TaskExecutor | DefaultType = DEFAULT,
    failback: type[BaseException] | None = None,
) -> type[BaseException]: ...
def _get_threading_timeout_exc_class() -> type[BaseException]: ...
def _get_eventlet_timeout_exc_class() -> type[BaseException]: ...
def _get_gevent_timeout_exc_class() -> type[BaseException]: ...
def _get_asyncio_timeout_exc_class() -> type[BaseException]: ...
def _get_curio_timeout_exc_class() -> type[BaseException]: ...
def _get_trio_timeout_exc_class() -> type[BaseException]: ...
def _get_anyio_timeout_exc_class() -> type[BaseException]: ...
def get_timeout_exc_class(
    *,
    executor: TaskExecutor | DefaultType = DEFAULT,
    failback: type[BaseException] | None = None,
) -> type[BaseException]: ...

_CancelledError: type[BaseException]
_TimeoutError: type[BaseException]
