#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2026 Ilya Egorov <0x42005e1f@gmail.com>
# SPDX-License-Identifier: ISC

import sys

from types import TracebackType
from typing import Any, Final

from aiologic.meta import SingletonEnum

if sys.version_info >= (3, 9):
    from typing import Literal
else:
    from typing_extensions import Literal

if sys.version_info >= (3, 11):
    from typing import Never
else:
    from typing_extensions import Never

if sys.version_info >= (3, 10):
    from typing import NewType
else:
    from typing_extensions import NewType

if sys.version_info >= (3, 11):
    from typing import final
else:
    from typing_extensions import final

RLockState = NewType("RLockState", tuple[int, int])
DummyLockState = NewType("DummyLockState", tuple[int, int])

@final
class LockType:
    __slots__ = (
        "__impl",
        "__weakref__",
    )

    def __init__(self, /) -> None: ...
    def __init_subclass__(cls, /, **kwargs: Any) -> Never: ...
    def __reduce__(self, /) -> Never: ...
    def __deepcopy__(self, memo: Any, /) -> Never: ...
    def __copy__(self, /) -> Never: ...
    def __repr__(self, /) -> str: ...
    def __enter__(self, /) -> bool: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
        /,
    ) -> None: ...
    def acquire(
        self,
        /,
        blocking: bool = True,
        timeout: float = -1,
    ) -> bool: ...
    def release(self, /) -> None: ...
    def locked(self, /) -> bool: ...
    def _at_fork_reinit(self, /) -> None: ...

@final
class RLockType:
    __slots__ = (
        "__impl",
        "__weakref__",
    )

    def __init__(self, /) -> None: ...
    def __init_subclass__(cls, /, **kwargs: Any) -> Never: ...
    def __reduce__(self, /) -> Never: ...
    def __deepcopy__(self, memo: Any, /) -> Never: ...
    def __copy__(self, /) -> Never: ...
    def __repr__(self, /) -> str: ...
    def __enter__(self, /) -> bool: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
        /,
    ) -> None: ...
    def acquire(
        self,
        /,
        blocking: bool = True,
        timeout: float = -1,
    ) -> bool: ...
    def release(self, /) -> None: ...
    def locked(self, /) -> bool: ...
    def _is_owned(self, /) -> bool: ...
    def _recursion_count(self, /) -> int: ...
    def _acquire_restore(self, state: RLockState, /) -> None: ...
    def _release_save(self, /) -> RLockState: ...
    def _at_fork_reinit(self, /) -> None: ...

@final
class DummyLockType(SingletonEnum):
    DUMMY_LOCK = "DUMMY_LOCK"  # ruff: ignore[unannotated-assignment-in-stub]

    def __init_subclass__(cls, /, **kwargs: Any) -> Never: ...
    def __enter__(self, /) -> Literal[True]: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
        /,
    ) -> None: ...
    def acquire(
        self,
        /,
        blocking: bool = True,
        timeout: float = -1,
    ) -> Literal[True]: ...
    def release(self, /) -> None: ...
    def locked(self, /) -> Literal[False]: ...
    def _is_owned(self, /) -> Literal[False]: ...
    def _recursion_count(self, /) -> Literal[0]: ...
    def _acquire_restore(self, state: DummyLockState, /) -> None: ...
    def _release_save(self, /) -> DummyLockState: ...
    def _at_fork_reinit(self, /) -> None: ...

DUMMY_LOCK: Final[Literal[DummyLockType.DUMMY_LOCK]]

def create_lock() -> LockType: ...
def create_rlock() -> RLockType: ...
def create_rlock_if_nogil() -> RLockType | DummyLockType: ...
def create_rlock_if_notso() -> RLockType | DummyLockType: ...
