#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2025 Ilya Egorov <0x42005e1f@gmail.com>
# SPDX-License-Identifier: ISC

import sys

if sys.version_info >= (3, 13):
    from warnings import deprecated
else:
    from typing_extensions import deprecated

def green_checkpoint_enabled() -> bool: ...
def async_checkpoint_enabled() -> bool: ...
def green_checkpoint(*, force: bool = False) -> None: ...
@deprecated("Use async_checkpoint() instead")
async def checkpoint(*, force: bool = False) -> None: ...
async def async_checkpoint(*, force: bool = False) -> None: ...
def green_checkpoint_if_cancelled(*, force: bool = False) -> None: ...
async def async_checkpoint_if_cancelled(*, force: bool = False) -> None: ...
