#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2025 Ilya Egorov <0x42005e1f@gmail.com>
# SPDX-License-Identifier: ISC

def green_checkpoint(*, force: bool = False) -> None: ...
async def async_checkpoint(*, force: bool = False) -> None: ...
def green_checkpoint_if_cancelled(*, force: bool = False) -> None: ...
async def async_checkpoint_if_cancelled(*, force: bool = False) -> None: ...
