#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2025 Ilya Egorov <0x42005e1f@gmail.com>
# SPDX-License-Identifier: ISC

def current_green_token() -> object: ...
def current_green_token_ident() -> tuple[str, int]: ...
def current_async_token() -> object: ...
def current_async_token_ident() -> tuple[str, int]: ...
def current_green_task() -> object: ...
def current_green_task_ident() -> tuple[str, int]: ...
def current_async_task() -> object: ...
def current_async_task_ident() -> tuple[str, int]: ...
