#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2025 Ilya Egorov <0x42005e1f@gmail.com>
# SPDX-License-Identifier: ISC

def _threading_sleep(seconds: float, /) -> None: ...
def _eventlet_sleep(seconds: float = 0, /) -> None: ...
def _gevent_sleep(seconds: float = 0, /) -> None: ...
async def _asyncio_sleep(seconds: float, /) -> None: ...
async def _curio_sleep(seconds: float, /) -> None: ...
